version: 2
updates:
    -   package-ecosystem: "npm"
        directory: "/"
        schedule:
            interval: "daily"
        assignees:
            - "sonicgd"
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "daily"
        assignees:
            - "sonicgd"
